// Generated by ReScript, PLEASE EDIT WITH CARE


var iconLinks = [
  "https://github.com/GuilhermeLLS",
  "https://www.linkedin.com/in/guilherme-luiz-lara-silva-9a7158162/",
  "https://twitter.com/gluizls"
];

var productData = [
  {
    img: {
      src: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=320&q=80",
      alt: "Solidario"
    },
    title: "Ajuda para ONGs: Solidario",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi quos quidem sequi illum facere recusandae voluptatibus"
  },
  {
    img: {
      src: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=320&q=80",
      alt: "Reda\xc3\xa7\xc3\xa3o Eficiente"
    },
    title: "Reda\xc3\xa7\xc3\xa3o Eficiente",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi quos quidem sequi illum facere recusandae voluptatibus"
  },
  {
    img: {
      src: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=320&q=80",
      alt: "React"
    },
    title: "CRA Template Kingdom",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi quos quidem sequi illum facere recusandae voluptatibus"
  }
];

var my_Img = "https://i.imgur.com/oWoxvzl.jpg";

export {
  iconLinks ,
  my_Img ,
  productData ,
  
}
/* No side effect */
