// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import Link from "next/link";
import * as PageContext from "../../contexts/PageContext/PageContext.js";
import * as IconsSection from "../IconsSection/IconsSection.js";
import * as React$1 from "@headlessui/react";

function Introduction(Props) {
  var match = React.useContext(PageContext.PageContext.context);
  var setCurrentPage = match.setCurrentPage;
  return React.createElement(React.Fragment, undefined, React.createElement("section", {
                  className: "flex justify-center w-screen h-screen dark:bg-white bg-gray-800"
                }, React.createElement(React$1.Transition, {
                      className: "flex flex-col items-center self-center",
                      as: "div",
                      appear: true,
                      show: true,
                      enter: "transform transition duration-700",
                      enterFrom: "opacity-0 scale-50",
                      enterTo: "opacity-100 scale-100",
                      leave: "transform duration-200 transition ease-in-out",
                      leaveFrom: "opacity-100 scale-100 ",
                      leaveTo: "opacity-0 scale-95",
                      children: null
                    }, React.createElement("div", {
                          className: "flex flex-col"
                        }, React.createElement("span", {
                              className: "text-2xl font-bold text-white dark:text-gray-800 md:text-2xl"
                            }, "Guilherme Luiz"), React.createElement("small", {
                              className: "text-sm text-white dark:text-gray-800 text-center"
                            }, "Software Engineer.")), React.createElement("div", {
                          className: "flex flex-row"
                        }, React.createElement("span", {
                              className: "text-xl cursor-pointer font-medium text-white dark:text-gray-700 hover:text-indigo-500 md:hover:text-indigo-100 dark:hover:text-indigo-400 m-4",
                              onClick: (function (param) {
                                  return Curry._1(setCurrentPage, (function (param) {
                                                return "about";
                                              }));
                                })
                            }, "About"), React.createElement("span", {
                              className: "text-xl cursor-pointer font-medium text-white dark:text-gray-700 hover:text-indigo-500 md:hover:text-indigo-100 dark:hover:text-indigo-400 m-4",
                              onClick: (function (param) {
                                  return Curry._1(setCurrentPage, (function (param) {
                                                return "mywork";
                                              }));
                                })
                            }, "My Work"), React.createElement(Link, {
                              href: "/blog",
                              children: React.createElement("a", {
                                    className: "text-xl font-medium text-white dark:text-gray-700 hover:text-indigo-500 md:hover:text-indigo-100 dark:hover:text-indigo-400 m-4"
                                  }, "Blog")
                            })), React.createElement(IconsSection.make, {
                          theme: "light"
                        }))));
}

var Link$1;

var make = Introduction;

export {
  Link$1 as Link,
  make ,
  
}
/* react Not a pure module */
