// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import Link from "next/link";
import * as IconsSection from "../IconsSection/IconsSection.js";
import * as React$1 from "@headlessui/react";

function Introduction(Props) {
  var match = React.useState(function () {
        return false;
      });
  var setIsShowing = match[1];
  return React.createElement(React.Fragment, undefined, React.createElement("button", {
                  onClick: (function (evt) {
                      return Curry._1(setIsShowing, (function (isShowing) {
                                    return !isShowing;
                                  }));
                    })
                }, "transition"), React.createElement(React$1.Transition, {
                  appear: true,
                  show: match[0],
                  enter: "transition-opacity duration-75",
                  enterFrom: "opacity-0",
                  enterTo: "opacity-100",
                  leave: "transition-opacity duration-150",
                  leaveFrom: "opacity-100",
                  leaveTo: "opacity-0",
                  children: "Teste"
                }), React.createElement("section", {
                  className: "flex justify-center w-screen h-screen dark:bg-white bg-gray-800"
                }, React.createElement("div", {
                      className: "flex flex-col items-center self-center"
                    }, React.createElement("div", {
                          className: "flex flex-col"
                        }, React.createElement("span", {
                              className: "text-2xl font-bold text-white dark:text-gray-800 md:text-2xl"
                            }, "Guilherme Luiz"), React.createElement("small", {
                              className: "text-sm text-white dark:text-gray-800 text-center"
                            }, "Software Engineer.")), React.createElement("div", {
                          className: "flex flex-row"
                        }, React.createElement("a", {
                              className: "text-xl font-medium text-white dark:text-gray-700 hover:text-indigo-500 md:hover:text-indigo-100 dark:hover:text-indigo-400 m-4",
                              href: "#about-me"
                            }, "About"), React.createElement("a", {
                              className: "text-xl font-medium text-white dark:text-gray-700 hover:text-indigo-500 md:hover:text-indigo-100 dark:hover:text-indigo-400 m-4",
                              href: "#my-work"
                            }, "My Work"), React.createElement(Link, {
                              href: "/blog",
                              children: React.createElement("a", {
                                    className: "text-xl font-medium text-white dark:text-gray-700 hover:text-indigo-500 md:hover:text-indigo-100 dark:hover:text-indigo-400 m-4"
                                  }, "Blog")
                            })), React.createElement(IconsSection.make, {
                          theme: "light"
                        }))));
}

var Link$1;

var make = Introduction;

export {
  Link$1 as Link,
  make ,
  
}
/* react Not a pure module */
