// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Caml_array from "bs-platform/lib/es6/caml_array.js";

function invertTheme(theme) {
  if (theme === "light") {
    return "dark";
  } else {
    return "light";
  }
}

function DarkModeButton(Props) {
  var match = React.useState(function () {
        return false;
      });
  var setDark = match[1];
  var dark = match[0];
  var onClick = function (evt) {
    evt.preventDefault();
    var currentTheme = dark ? "dark" : "light";
    Caml_array.get(document.getElementsByTagName("BODY"), 0).classList.remove(currentTheme);
    Curry._1(setDark, (function (prevState) {
            return !prevState;
          }));
    return Caml_array.get(document.getElementsByTagName("BODY"), 0).classList.add(invertTheme(currentTheme));
  };
  return React.createElement("div", {
              className: "dark:text-white fixed bottom-6 right-6 lg:bottom-20 lg:right-10"
            }, React.createElement("button", {
                  onClick: onClick
                }, dark ? React.createElement("svg", {
                        className: "w-8 h-8 md:w-10 md:h-10",
                        fill: "none",
                        stroke: "currentColor",
                        viewBox: "0 0 24 24",
                        xmlns: "http://www.w3.org/2000/svg"
                      }, React.createElement("path", {
                            d: "M12 3v1m0 16v1m9-9h-1M4 12H3m15.364 6.364l-.707-.707M6.343 6.343l-.707-.707m12.728 0l-.707.707M6.343 17.657l-.707.707M16 12a4 4 0 11-8 0 4 4 0 018 0z",
                            strokeLinecap: "round",
                            strokeLinejoin: "round",
                            strokeWidth: "2"
                          })) : React.createElement("svg", {
                        className: "w-8 h-8 md:w-10 md:h-10",
                        fill: "none",
                        stroke: "currentColor",
                        viewBox: "0 0 24 24",
                        xmlns: "http://www.w3.org/2000/svg"
                      }, React.createElement("path", {
                            d: "M20.354 15.354A9 9 0 018.646 3.646 9.003 9.003 0 0012 21a9.003 9.003 0 008.354-5.646z",
                            strokeLinecap: "round",
                            strokeLinejoin: "round",
                            strokeWidth: "2"
                          }))));
}

var make = DarkModeButton;

export {
  make ,
  
}
/* react Not a pure module */
