// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function MyWork(Props) {
  return React.createElement("section", {
              className: "mx-6 my-6"
            }, React.createElement("h3", {
                  className: "text-3xl font-bold text-gray-800 dark:text-gray-100 mb-4"
                }, "My work"), React.createElement("div", {
                  className: "flex md:flex-row flex-col"
                }, React.createElement("div", {
                      className: "max-w-xs mt-4 md:mt-0 mx-auto overflow-hidden bg-white rounded-lg shadow-lg dark:bg-gray-800"
                    }, React.createElement("div", {
                          className: "px-4 py-2"
                        }, React.createElement("h1", {
                              className: "text-3xl font-bold text-gray-800 uppercase dark:text-white"
                            }, "Ajuda para ONGs: Solid\xc3\xa1rio"), React.createElement("p", {
                              className: "mt-1 text-sm text-gray-600 dark:text-gray-400"
                            }, "Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi quos quidem sequi illum facere recusandae voluptatibus")), React.createElement("img", {
                          className: "object-cover w-full h-48 mt-2",
                          alt: "NIKE AIR",
                          src: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=320&q=80"
                        })), React.createElement("div", {
                      className: "max-w-xs mt-4 md:mt-0 mx-auto overflow-hidden bg-white rounded-lg shadow-lg dark:bg-gray-800"
                    }, React.createElement("div", {
                          className: "px-4 py-2"
                        }, React.createElement("h1", {
                              className: "text-3xl font-bold text-gray-800 uppercase dark:text-white"
                            }, "Reda\xc3\xa7\xc3\xa3o Eficiente"), React.createElement("p", {
                              className: "mt-1 text-sm text-gray-600 dark:text-gray-400"
                            }, "Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi quos quidem sequi illum facere recusandae voluptatibus")), React.createElement("img", {
                          className: "object-cover w-full h-48 mt-2",
                          alt: "NIKE AIR",
                          src: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=320&q=80"
                        })), React.createElement("div", {
                      className: "max-w-xs mt-4 md:mt-0 mx-auto overflow-hidden bg-white rounded-lg shadow-lg dark:bg-gray-800"
                    }, React.createElement("div", {
                          className: "px-4 py-2"
                        }, React.createElement("h1", {
                              className: "text-3xl font-bold text-gray-800 uppercase dark:text-white"
                            }, "CRA Template Kingdom"), React.createElement("p", {
                              className: "mt-1 text-sm text-gray-600 dark:text-gray-400"
                            }, "Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi quos quidem sequi illum facere recusandae voluptatibus")), React.createElement("img", {
                          className: "object-cover w-full h-48 mt-2",
                          alt: "NIKE AIR",
                          src: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=320&q=80"
                        }))));
}

var make = MyWork;

export {
  make ,
  
}
/* react Not a pure module */
