// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import Link from "next/link";
import * as Caml_array from "bs-platform/lib/es6/caml_array.js";
import * as IconsSection from "../IconsSection/IconsSection.js";

function Sidebar(Props) {
  var match = React.useState(function () {
        return false;
      });
  var setSidebarOpen = match[1];
  var openSidebar = match[0];
  var onClick = function (evt) {
    evt.preventDefault();
    var tmp = Caml_array.get(document.getElementsByTagName("BODY"), 0).style;
    tmp.overflow = openSidebar ? "auto" : "hidden";
    return Curry._1(setSidebarOpen, (function (prev) {
                  return !prev;
                }));
  };
  return React.createElement(React.Fragment, undefined, React.createElement("div", {
                  className: "flex md:hidden px-6 pt-4 z-10"
                }, React.createElement("button", {
                      "aria-label": "toggle menu",
                      className: "text-gray-500 dark:text-gray-200 hover:text-indigo-500 dark:hover:text-indigo-200 focus:outline-none focus:text-indigo-500 dark:focus:text-indigo-400",
                      onClick: onClick
                    }, openSidebar ? React.createElement("svg", {
                            className: "w-6 h-6",
                            viewBox: "0 0 24 24",
                            xmlns: "http://www.w3.org/2000/svg"
                          }, React.createElement("path", {
                                d: "M14.53 4.53l-1.06-1.06L9 7.94 4.53 3.47 3.47 4.53 7.94 9l-4.47 4.47 1.06 1.06L9 10.06l4.47 4.47 1.06-1.06L10.06 9z"
                              })) : React.createElement("svg", {
                            className: "w-6 h-6",
                            viewBox: "0 0 24 24"
                          }, React.createElement("path", {
                                d: "M4 5h16a1 1 0 0 1 0 2H4a1 1 0 1 1 0-2zm0 6h16a1 1 0 0 1 0 2H4a1 1 0 0 1 0-2zm0 6h16a1 1 0 0 1 0 2H4a1 1 0 0 1 0-2z",
                                fillRule: "evenodd"
                              })))), React.createElement("aside", {
                  className: "md:flex " + (
                    openSidebar ? "flex" : "hidden"
                  ) + " absolute md:fixed transition duration-300 ease-in-out items-center h-screen px-20 dark:bg-white bg-gray-800"
                }, React.createElement("div", {
                      className: "flex flex-col items-center"
                    }, React.createElement("a", {
                          className: "text-2xl font-bold text-white dark:text-gray-800 md:text-2xl hover:text-indigo-500 md:hover:text-indigo-100 dark:hover:text-indigo-200 md:mb-10",
                          href: "#",
                          onClick: onClick
                        }, "Navigation"), React.createElement("a", {
                          className: "text-xl font-medium text-white dark:text-gray-700 hover:text-indigo-500 md:hover:text-indigo-100 dark:hover:text-indigo-400 md:mx-4 md:my-3",
                          href: "#about-me",
                          onClick: onClick
                        }, "About"), React.createElement("a", {
                          className: "text-xl font-medium text-white dark:text-gray-700 hover:text-indigo-500 md:hover:text-indigo-100 dark:hover:text-indigo-400 md:mx-4 md:my-3",
                          href: "#my-work",
                          onClick: onClick
                        }, "My Work"), React.createElement(Link, {
                          href: "/blog",
                          children: React.createElement("a", {
                                className: "text-xl font-medium text-white dark:text-gray-700 hover:text-indigo-500 md:hover:text-indigo-100 dark:hover:text-indigo-400 md:mx-4 md:my-3",
                                onClick: onClick
                              }, "Blog")
                        }), React.createElement(IconsSection.make, {
                          theme: "light"
                        }))));
}

var Link$1;

var make = Sidebar;

export {
  Link$1 as Link,
  make ,
  
}
/* react Not a pure module */
