// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as PageContext from "../../contexts/PageContext/PageContext.js";
import * as React$1 from "@headlessui/react";

function PageWrapper(Props) {
  var children = Props.children;
  var match = React.useContext(PageContext.PageContext.context);
  var setCurrentPage = match.setCurrentPage;
  return React.createElement(React$1.Transition, {
              className: "px-10 py-3 h-screen absolute bg-white md:relative md:w-216",
              as: "section",
              show: true,
              enter: "transition ease-in-out duration-1300 transform",
              enterFrom: "translate-x-full",
              enterTo: "translate-x-0",
              leave: "transition ease-in-out duration-1300 transform",
              leaveFrom: "translate-x-0",
              leaveTo: "translate-x-full",
              children: null
            }, React.createElement("svg", {
                  className: "w-6 h-6 mb-4 cursor-pointer",
                  onClick: (function (param) {
                      return Curry._1(setCurrentPage, (function (param) {
                                    return "main";
                                  }));
                    }),
                  viewBox: "0 0 24 24",
                  xmlns: "http://www.w3.org/2000/svg"
                }, React.createElement("path", {
                      d: "M14.53 4.53l-1.06-1.06L9 7.94 4.53 3.47 3.47 4.53 7.94 9l-4.47 4.47 1.06 1.06L9 10.06l4.47 4.47 1.06-1.06L10.06 9z"
                    })), children);
}

var make = PageWrapper;

export {
  make ,
  
}
/* react Not a pure module */
