// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Blog$default(Props) {
  return React.createElement("h1", {
              className: "text-3xl text-indigo-500"
            }, "blog coming soon...");
}

var $$default = Blog$default;

export {
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
