// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Footer from "./components/Footer/Footer.js";
import * as MyWork from "./components/MyWork/MyWork.js";
import * as Navbar from "./components/Navbar/Navbar.js";
import * as AboutMe from "./components/AboutMe/AboutMe.js";

function $$default(param) {
  return React.createElement(React.Fragment, undefined, React.createElement(Navbar.make, {}), React.createElement(AboutMe.make, {}), React.createElement(MyWork.make, {}), React.createElement(Footer.make, {}));
}

export {
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
