// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Introduction from "./components/Introduction/Introduction.js";

function $$default(param) {
  return React.createElement(Introduction.make, {});
}

export {
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
