// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as PageWrapper from "../PageWrapper/PageWrapper.js";

function AboutMe(Props) {
  return React.createElement(PageWrapper.make, {
              children: null
            }, React.createElement("h2", {
                  className: "text-3xl font-bold text-gray-800"
                }, "About me"), React.createElement("p", {
                  className: "mt-4 text-gray-500"
                }, "Hello 👋"), React.createElement("p", {
                  className: "mt-4 text-gray-500"
                }, "I'm a software engineer and huge tech enthusiast. I began my carreer building crawlers with Nodejs and Typescript. Nowadays, as a JavaScript focused developer, I spend a lot of time architeting and building solutions for the web using the React/NodeJs stack."), React.createElement("p", {
                  className: "mt-4 text-gray-500"
                }, "I'm always happy and excited to learn something new. Lately, I've been trying some Elixir with Phoenix and some Rescript. I'm also into SEO reliant development, performance and great user experience are a must for me."), React.createElement("p", {
                  className: "mt-4 text-gray-500"
                }, "If you are interested into learning a little bit more about my work, you can check my ", React.createElement("a", {
                      className: "text-indigo-500 font-bold",
                      href: "https://github.com/GuilhermeLLS",
                      rel: "nofollow noreferrer"
                    }, "Github"), " or/and ", React.createElement("a", {
                      className: "text-indigo-500 font-bold",
                      href: "https://github.com/GuilhermeLLS",
                      rel: "nofollow noreferrer"
                    }, "Resume"), ", visit the ", React.createElement("code", {
                      className: "text-indigo-500 bg-indigo-100 p-1"
                    }, "My Work"), " section in this website 🤠."));
}

var make = AboutMe;

export {
  make ,
  
}
/* react Not a pure module */
