name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

env:
  bucket: guilhermeluiz.dev

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      
      - name: Install Dependencies
        run: yarn install
      
      - name: Run tests
        run: yarn test --watchAll false
      
      - name: Build App
        run: yarn build
        
      - uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
          
      - name: See files
        run: ls
      - name: Upload files to bucket
        run: gsutil -m cp -r build/* gs://"$BUCKET"
      
      - name: Allow AllUsers
        run: gsutil -m acl ch -R AllUsers:R gs://"$BUCKET"
        
      - name: Set cache for static files
        run: gsutil setmeta -h "Cache-Control:public, max-age=15678000" gs://"$BUCKET"/**/*.{png,svg,css,js}
      
      - name: Set Cache for index.html
        run: gsutil setmeta -h "Cache-Control:no-cache, no-store" gs://"$BUCKET"/index.html
